version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/clean_old_files.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root



